version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - /data/mongo:/data/mongo
    networks:
      - my_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - my_network

networks:
  my_network:

volumes:
  mongo_data:
