version: '3.8'

services:
  php:
    image: php:8.3-fpm
    container_name: php-fpm
    volumes:
      - ./source:/var/www/html

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8111:8111"
    volumes:
      - ./source:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php